# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	minecraft_version=1.21.1
	yarn_mappings=1.21.1+build.3
	loader_version=0.16.5

# Mod Properties
	mod_version = 1.13.0-alpha.10+mc.1.21.x
	maven_group = io.github.apace100
	archives_base_name = Origins

# Dependencies
	fabric_version=0.105.0+1.21.1
	apoli_version=2.12.0-alpha.14+mc.1.21.x
	clothconfig_version=13.0.121
	modmenu_version=9.0.0
	carpet_version=1.21-1.4.147+v240613
