# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	minecraft_version=1.20.1
	yarn_mappings=1.20.1+build.10
	loader_version=0.15.11

# Mod Properties
	mod_version = 1.10.2+mc.1.20.x
	maven_group = io.github.apace100
	archives_base_name = Origins

# Dependencies
	fabric_version=0.92.2+1.20.1
	cca_version=5.1.0
	apoli_version=2.9.2+mc.1.20.x
	reach_version=2.4.0
	clothconfig_version=10.0.96
	modmenu_version=6.2.1
	mixinsquared=0.3.7-beta.1