modLoader="javafml"
loaderVersion="[47,)" # 47 = Forge 1.20.1+
license="MIT"

[properties]
"connector:placeholder"=true

[[mods]]
modId="origins"
version="${file.jarVersion}"
displayName="Origins"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/origins"
displayURL="https://www.curseforge.com/minecraft/mc-mods/origins"
authors="Apace"
description='''
This mod adds several origins with passive abilities to the game, which you can choose from at the beginning of the game.
'''

[[dependencies.origins]]
modId="connectormod"
mandatory=true
versionRange="[1.0.0-beta.46,)"
ordering="NONE"
side="BOTH"

[[dependencies.origins]]
modId="connectorextras"
mandatory=true
versionRange="[1.0.0,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.origins]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
